indent_type = "Spaces"
indent_width = 2
column_width = 120
line_endings = "Unix"
quote_style = "AutoPreferDouble"
no_call_parentheses = false
collapse_simple_statement = "Always"

[sort_requires]
enabled = false
